name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      COSIGN_EXPERIMENTAL: "true"
      KO_DOCKER_REPO: ghcr.io/puerco/supply-chain-demo/octosay

    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3

      - name: setup go environment
        uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v3.0.0
        with:
          go-version: '1.17.x'

      - name: Install Kubernetes SBOM Tool
        uses: puerco/bom-installer@aa0837e37b6965b5fc50adfad0683ec3c0a2c2c4

      - name: Install sigstore cosign
        uses: sigstore/cosign-installer@581838fbedd492d2350a9ecd427a95d6de1e5d01 # v2.1.0

      - name: Login to Docker Registry
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # v1.14.1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Get TAG
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: build Image
        run: go run mage.go buildImages

      - name: Build the outside SBOM
        run: |
          set -e
          bom generate -o /tmp/sbom.spdx -c .sbom.yaml
      - name: Attach SBOM
        run: |
          set -e
          cosign attach sbom --sbom /tmp/sbom.spdx ghcr.io/puerco/supply-chain-demo/octosay:${{ steps.get_tag.outputs.TAG }}